---
name: DNSControl Action
description: Deploy your DNS configuration to multiple providers
author: Koen Rouwhorst <info@koenrouwhorst.nl>
branding:
  icon: cloud
  color: yellow
inputs:
  args:
    description: DNSControl command
    required: true
  dnscontrol_config_file:
    description: Path to DNS configuration file.
    required: false
    default: '.'
  dnscontrol_creds_file:
    description: Path to DNS credentials file.
    required: false
    default: '.'
outputs:
  output:
    description: The output of the dnscontrol command that was executed.
runs:
  using: docker
  image: 'Dockerfile'
