---
name: DNSControl Action
description: Deploy your DNS configuration to multiple providers
author: Koen Rouwhorst <info@koenrouwhorst.nl>
branding:
  icon: cloud
  color: yellow
inputs:
  args:
    description: DNSControl command
    required: true
  working_dir:
    description: Working directory location of dnsconfig.js
    required: false
    default: '.'
outputs:
  output:
    description: The output of the dnscontrol command that was executed.
runs:
  using: docker
  image: 'Dockerfile'
